// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("constrainedtypes.DesignTime")>]
[<assembly: AssemblyProductAttribute("constrainedtypes")>]
[<assembly: AssemblyDescriptionAttribute("This library is for the .NET platform implementing constrainedtypes.")>]
[<assembly: AssemblyVersionAttribute("1.0.0")>]
[<assembly: AssemblyFileVersionAttribute("1.0.0")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "constrainedtypes.DesignTime"
    let [<Literal>] AssemblyProduct = "constrainedtypes"
    let [<Literal>] AssemblyDescription = "This library is for the .NET platform implementing constrainedtypes."
    let [<Literal>] AssemblyVersion = "1.0.0"
    let [<Literal>] AssemblyFileVersion = "1.0.0"
